// ** C1Cerr Class ** //
// Autogenerated in QDP Commands ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_CERR_H
#define _MZN_CMD_C1_CERR_H

#include "command.h"

namespace mzn {
class C1Cerr : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Cerr const & cmd);

public:

    explicit C1Cerr();
    ~C1Cerr() = default;

    C1Cerr(C1Cerr && rhs) = default;
    C1Cerr & operator=(C1Cerr && rhs) = default;
    C1Cerr(C1Cerr const & rhs) = default;
    C1Cerr & operator=(C1Cerr const & rhs) = default;
    std::string const cmd_name = "c1_cerr";

    BmCerr error_code;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Cerr const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_CERR_H
