// ** C1Ctrl Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_CTRL_H
#define _MZN_CMD_C1_CTRL_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Ctrl : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Ctrl const & cmd);

public:

    explicit C1Ctrl();
    ~C1Ctrl() = default;

    C1Ctrl(C1Ctrl && rhs) = default;
    C1Ctrl & operator=(C1Ctrl && rhs) = default;
    C1Ctrl(C1Ctrl const & rhs) = default;
    C1Ctrl & operator=(C1Ctrl const & rhs) = default;
    std::string const cmd_name = "c1_ctrl";

    BmCtrlFlags ctrl_flags;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Ctrl const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_CTRL_H
