// ** C1Mysn Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_MYSN_H
#define _MZN_CMD_C1_MYSN_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Mysn : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Mysn const & cmd);

public:

    explicit C1Mysn();
    ~C1Mysn() = default;

    C1Mysn(C1Mysn && rhs) = default;
    C1Mysn & operator=(C1Mysn && rhs) = default;
    C1Mysn(C1Mysn const & rhs) = default;
    C1Mysn & operator=(C1Mysn const & rhs) = default;
    std::string const cmd_name = "c1_mysn";

    CmdFieldHex<uint64_t> serial_number;
    CmdField<uint32_t> kmi_property_tag;
    CmdField<uint32_t> user_tag;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Mysn const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_MYSN_H
