// ** C1Pulse Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_PULSE_H
#define _MZN_CMD_C1_PULSE_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Pulse : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Pulse const & cmd);

public:

    explicit C1Pulse();
    ~C1Pulse() = default;

    C1Pulse(C1Pulse && rhs) = default;
    C1Pulse & operator=(C1Pulse && rhs) = default;
    C1Pulse(C1Pulse const & rhs) = default;
    C1Pulse & operator=(C1Pulse const & rhs) = default;
    std::string const cmd_name = "c1_pulse";

    CmdField<bool, 1> sensor_control_active_high;
    BmSensorControlMap sensor_control_map;
    CmdFieldDuration<uint16_t, std::centi> pulse_duration;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Pulse const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_PULSE_H
