// ** C1Pollsn Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_POLLSN_H
#define _MZN_CMD_C1_POLLSN_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Pollsn : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Pollsn const & cmd);

public:

    explicit C1Pollsn();
    ~C1Pollsn() = default;

    C1Pollsn(C1Pollsn && rhs) = default;
    C1Pollsn & operator=(C1Pollsn && rhs) = default;
    C1Pollsn(C1Pollsn const & rhs) = default;
    C1Pollsn & operator=(C1Pollsn const & rhs) = default;
    std::string const cmd_name = "c1_pollsn";

    CmdFieldHex<uint16_t> serial_number_mask;
    CmdFieldHex<uint16_t> serial_number_match;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Pollsn const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_POLLSN_H
