// ** C1Ping3 Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_PING_3_H
#define _MZN_CMD_C1_PING_3_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Ping3 : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Ping3 const & cmd);

public:

    explicit C1Ping3();
    ~C1Ping3() = default;

    C1Ping3(C1Ping3 && rhs) = default;
    C1Ping3 & operator=(C1Ping3 && rhs) = default;
    C1Ping3(C1Ping3 const & rhs) = default;
    C1Ping3 & operator=(C1Ping3 const & rhs) = default;
    std::string const cmd_name = "c1_ping_3";

    CmdField<uint16_t> ping_type;
    CmdField<uint16_t> user_message_number;
    CmdField<uint16_t> drift_tolerance;
    CmdField<uint16_t> user_message_count;
    CmdFieldTime<uint32_t, Time::k_shift_seconds_1970_2000> time_of_last_reboot;
    CmdFieldIgnore<uint32_t> spare_0;
    CmdFieldIgnore<uint32_t> spare_1;
    BmRqstat status_bitmap;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Ping3 const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_PING_3_H
