// ** C1Ping4 Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_PING_4_H
#define _MZN_CMD_C1_PING_4_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Ping4 : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Ping4 const & cmd);

public:

    explicit C1Ping4();
    ~C1Ping4() = default;

    C1Ping4(C1Ping4 && rhs) = default;
    C1Ping4 & operator=(C1Ping4 && rhs) = default;
    C1Ping4(C1Ping4 const & rhs) = default;
    C1Ping4 & operator=(C1Ping4 const & rhs) = default;
    std::string const cmd_name = "c1_ping_4";

    CmdField<uint16_t> ping_type;
    CmdFieldIgnore<uint16_t> ignore_0;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Ping4 const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_PING_4_H
