// ** C1Rqstat Class ** //
// Autogenerated in QDP Commands ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_RQSTAT_H
#define _MZN_CMD_C1_RQSTAT_H

#include "command.h"

namespace mzn {
class C1Rqstat : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Rqstat const & cmd);

public:

    explicit C1Rqstat();
    ~C1Rqstat() = default;

    C1Rqstat(C1Rqstat && rhs) = default;
    C1Rqstat & operator=(C1Rqstat && rhs) = default;
    C1Rqstat(C1Rqstat const & rhs) = default;
    C1Rqstat & operator=(C1Rqstat const & rhs) = default;
    std::string const cmd_name = "c1_rqstat";

    BmRqstat request_bitmap;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Rqstat const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_RQSTAT_H
