// ** C1Rqglob Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_RQGLOB_H
#define _MZN_CMD_C1_RQGLOB_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Rqglob : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Rqglob const & cmd);

public:

    explicit C1Rqglob();
    ~C1Rqglob() = default;

    C1Rqglob(C1Rqglob && rhs) = default;
    C1Rqglob & operator=(C1Rqglob && rhs) = default;
    C1Rqglob(C1Rqglob const & rhs) = default;
    C1Rqglob & operator=(C1Rqglob const & rhs) = default;
    std::string const cmd_name = "c1_rqglob";


    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Rqglob const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_RQGLOB_H
