// ** C1Rqdev Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_RQDEV_H
#define _MZN_CMD_C1_RQDEV_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Rqdev : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Rqdev const & cmd);

public:

    explicit C1Rqdev();
    ~C1Rqdev() = default;

    C1Rqdev(C1Rqdev && rhs) = default;
    C1Rqdev & operator=(C1Rqdev && rhs) = default;
    C1Rqdev(C1Rqdev const & rhs) = default;
    C1Rqdev & operator=(C1Rqdev const & rhs) = default;
    std::string const cmd_name = "c1_rqdev";


    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Rqdev const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_RQDEV_H
