// ** C2Regchk Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C2_REGCHK_H
#define _MZN_CMD_C2_REGCHK_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C2Regchk : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C2Regchk const & cmd);

public:

    explicit C2Regchk();
    ~C2Regchk() = default;

    C2Regchk(C2Regchk && rhs) = default;
    C2Regchk & operator=(C2Regchk && rhs) = default;
    C2Regchk(C2Regchk const & rhs) = default;
    C2Regchk & operator=(C2Regchk const & rhs) = default;
    std::string const cmd_name = "c2_regchk";

    CmdFieldIp ip_address;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C2Regchk const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C2_REGCHK_H
