// ** CxEnvironmentalProcessorStatus Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_CX_ENVIRONMENTAL_PROCESSOR_STATUS_H
#define _MZN_CMD_CX_ENVIRONMENTAL_PROCESSOR_STATUS_H

#include "command.h"


#include "cy_environmental_processor_status.h"

#define k_cy_environmental_processor_status 0

#include "multi_command.h"
namespace mzn {

// -------------------------------------------------------------------------- //
class CxEnvironmentalProcessorStatus : public MultiCommand {

friend std::ostream & operator<<(std::ostream & cmd_os, CxEnvironmentalProcessorStatus const & cmd);

public:

    explicit CxEnvironmentalProcessorStatus();
    ~CxEnvironmentalProcessorStatus() = default;

    CxEnvironmentalProcessorStatus(CxEnvironmentalProcessorStatus && rhs) = default;
    CxEnvironmentalProcessorStatus & operator=(CxEnvironmentalProcessorStatus && rhs) = default;
    std::string const cmd_name = "cx_environmental_processor_status";


    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;
    // max keys implementation in a separate function/file
    // not part of auto generation
    int number_of_ic(std::size_t const msg_size) const override;
    void create_new_ic(uint8_t const  cmd_key) override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, CxEnvironmentalProcessorStatus const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_CX_ENVIRONMENTAL_PROCESSOR_STATUS_H
