// ** CyArpStatus Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_CY_ARP_STATUS_H
#define _MZN_CMD_CY_ARP_STATUS_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class CyArpStatus : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, CyArpStatus const & cmd);

public:

    explicit CyArpStatus();
    ~CyArpStatus() = default;

    CyArpStatus(CyArpStatus && rhs) = default;
    CyArpStatus & operator=(CyArpStatus && rhs) = default;
    CyArpStatus(CyArpStatus const & rhs) = default;
    CyArpStatus & operator=(CyArpStatus const & rhs) = default;
    std::string const cmd_name = "cy_arp_status";

    CmdFieldIp ip_address;
    CmdField<uint64_t, 6> mac_address;
    CmdFieldDuration<uint16_t> timeout;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, CyArpStatus const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_CY_ARP_STATUS_H
