// ** CzInternalTemperatureMeasurement Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_CZ_INTERNAL_TEMPERATURE_MEASUREMENT_H
#define _MZN_CMD_CZ_INTERNAL_TEMPERATURE_MEASUREMENT_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class CzInternalTemperatureMeasurement : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, CzInternalTemperatureMeasurement const & cmd);

public:

    explicit CzInternalTemperatureMeasurement();
    ~CzInternalTemperatureMeasurement() = default;

    CzInternalTemperatureMeasurement(CzInternalTemperatureMeasurement && rhs) = default;
    CzInternalTemperatureMeasurement & operator=(CzInternalTemperatureMeasurement && rhs) = default;
    CzInternalTemperatureMeasurement(CzInternalTemperatureMeasurement const & rhs) = default;
    CzInternalTemperatureMeasurement & operator=(CzInternalTemperatureMeasurement const & rhs) = default;
    std::string const cmd_name = "cz_internal_temperature_measurement";

    CmdField<int32_t> internal_temperature_measurement;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, CzInternalTemperatureMeasurement const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_CZ_INTERNAL_TEMPERATURE_MEASUREMENT_H
