// ** QdpCrc Class ** //
// Autogenerated in QDP Commands ** //
// Manzano Software //

#ifndef _MZN_CMD_QDP_CRC_H
#define _MZN_CMD_QDP_CRC_H

#include "command.h"

namespace mzn {
class QdpCrc : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, QdpCrc const & cmd);

public:

    explicit QdpCrc();
    ~QdpCrc() = default;

    QdpCrc(QdpCrc && rhs) = default;
    QdpCrc & operator=(QdpCrc && rhs) = default;
    QdpCrc(QdpCrc const & rhs) = default;
    QdpCrc & operator=(QdpCrc const & rhs) = default;
    std::string const cmd_name = "qdp_crc";

    CmdFieldArrayUByte<4> crc;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, QdpCrc const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_QDP_CRC_H
