// ** QdpHeader Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_QDP_HEADER_H
#define _MZN_CMD_QDP_HEADER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class QdpHeader : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, QdpHeader const & cmd);

public:

    explicit QdpHeader();
    ~QdpHeader() = default;

    QdpHeader(QdpHeader && rhs) = default;
    QdpHeader & operator=(QdpHeader && rhs) = default;
    QdpHeader(QdpHeader const & rhs) = default;
    QdpHeader & operator=(QdpHeader const & rhs) = default;
    std::string const cmd_name = "qdp_header";

    CmdFieldHex<uint8_t> command_number;
    CmdField<uint8_t> firmware_version;
    CmdField<uint16_t> length;
    CmdField<uint16_t> sequence_number;
    CmdField<uint16_t> acknowledge_number;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, QdpHeader const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_QDP_HEADER_H
